"""empty message

Revision ID: 00b800fef4a8
Revises: b42b7322a2f1
Create Date: 2019-04-06 12:05:42.303725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b800fef4a8'
down_revision = 'b42b7322a2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('Users', sa.Column('protrait', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'protrait')
    op.drop_column('Users', 'name')
    # ### end Alembic commands ###
