"""empty message

Revision ID: 2cc910b6d14c
Revises: afdd87e606f0
Create Date: 2019-04-04 12:02:44.630812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc910b6d14c'
down_revision = 'afdd87e606f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Projects', sa.Column('is_public', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Projects', 'is_public')
    # ### end Alembic commands ###
