"""empty message

Revision ID: 3ab61dfbd0ca
Revises: e74b7ec40525
Create Date: 2019-03-30 16:14:03.083495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab61dfbd0ca'
down_revision = 'e74b7ec40525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FavoriteSpots', sa.Column('created_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('FavoriteSpots', sa.Column('update_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FavoriteSpots', 'update_time')
    op.drop_column('FavoriteSpots', 'created_time')
    # ### end Alembic commands ###
