"""empty message

Revision ID: 4da33ddd968d
Revises: 2cc910b6d14c
Create Date: 2019-04-05 15:54:46.508023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da33ddd968d'
down_revision = '2cc910b6d14c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RecRecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rec_list', sa.String(length=50000), nullable=False),
    sa.Column('last_favorite_list', sa.String(length=300), nullable=False),
    sa.Column('last_query_zones', sa.String(length=2000), nullable=True),
    sa.Column('last_query_keyword', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RecRecords')
    # ### end Alembic commands ###
