"""empty message

Revision ID: a9ec654b6b8f
Revises: 893687124138
Create Date: 2019-04-13 11:19:13.665822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ec654b6b8f'
down_revision = '893687124138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Spots', sa.Column('del_pic1', sa.String(length=100), nullable=True))
    op.add_column('Spots', sa.Column('del_pic2', sa.String(length=100), nullable=True))
    op.add_column('Spots', sa.Column('del_pic3', sa.String(length=100), nullable=True))
    op.add_column('Spots', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Spots', 'Users', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Spots', type_='foreignkey')
    op.drop_column('Spots', 'owner')
    op.drop_column('Spots', 'del_pic3')
    op.drop_column('Spots', 'del_pic2')
    op.drop_column('Spots', 'del_pic1')
    # ### end Alembic commands ###
