"""empty message

Revision ID: afdd87e606f0
Revises: 29c92d7cf586
Create Date: 2019-04-01 22:13:30.512031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'afdd87e606f0'
down_revision = '29c92d7cf586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Projects', sa.Column('tot_days', sa.Integer(), nullable=False))
    op.drop_column('Projects', 'end_day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Projects', sa.Column('end_day', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('Projects', 'tot_days')
    # ### end Alembic commands ###
