"""empty message

Revision ID: b42b7322a2f1
Revises: 4da33ddd968d
Create Date: 2019-04-05 19:59:22.685978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42b7322a2f1'
down_revision = '4da33ddd968d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Spots', sa.Column('rec_table', sa.String(length=50000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Spots', 'rec_table')
    # ### end Alembic commands ###
